### ISSUE TITLE
package loading failed

### ISSUE THREAD

**Issue by edifice1989** [bblodfon/emba#2]
library(emba)
Error: package or namespace load failed for ‘emba’:
 object ‘all_of’ is not exported by 'namespace:tidyselect'

**Comment by bblodfon** [comment]
Hi @edifice1989, I believe this has to do with me not specifying the exact minimum version of `tidyselect` in the `DESCRIPTION` file. Can you quickly check the version you are using with `packageVersion("tidyselect")`? (if it's `0.2.5` or earlier then there is no `all_of` in there :)

**Comment by edifice1989** [comment]
packageVersion("tidyselect")
[1] ‘0.2.5’

**Comment by bblodfon** [comment]
This should be fixed now - can you try now installing the development version with `remotes::install_github("bblodfon/emba")`? It should force now to install and import the newer version of `tidyselect`.

There is also a problem since the last 8 hours or so with https://travis-ci.com/ so I cannot test this version with CI right now, but with `devtools::check_rhub()` I tested its installation in 3 major platoforms and the results were succesfull. For example: https://builder.r-hub.io/status/emba_0.1.7.tar.gz-8feddab76c6b4695953769e92bfa5728 (`tidyselect` is installed at `1.1.0` version in a machine that does not have this library at all). I guess what happened in your case is that you had it installed a long time ago in a previous version and since I didn't specify the minimum version I needed, the installation did not update it and thus it failed to load the function I needed from that package.

**Comment by bblodfon** [comment]
The travis issue is also now fixed.
